[package]
name = "cusf_sidechain_types"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitcoin = { version = "0.32.2", features = ["serde"] }
blake3 = "1.5.4"
bs58 = { version = "0.5.1", features = ["check"] }
serde = "1.0.209"
